package jlox.lexer;

public enum TokenType {
    // SINGLE CHARACTER TOKENS
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,  
    COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,

    // ONE OR TWO CHARACTER TOKENS, CHARACTERS CAN CAUSE CONFUSION SO GROUP THEM HERE
    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,

    // LITERAL VALUES
    IDENTIFIER, STRING, NUMBER,

    // KEYWORDS
    AND, OR, CLASS, FUN, ELSE, IF, FOR, NIL, FALSE,
    PRINT, RETURN, SUPER, THIS, VAR, WHILE, TRUE,

    EOF
} 